#!/bin/bash
#Author: Khaja Minhajuddin
#Script to run a command in background redirecting the
#STDERR and STDOUT to /tmp/b.log in a background task

echo "$(date +%Y-%m-%d:%H:%M:%S): started running $@" >> /tmp/b.log
rawcmd="$@"
cmd="time $1"
shift
($cmd "$@" 1>> /tmp/b.log 2>&1; notify-send --urgency=low -i "$([ $? = 0 ] && echo '/home/minhajuddin/.icons/ruby_green_icon.png' || echo error)" "$rawcmd")&>/dev/null &
