#!/bin/bash

if [[ -z $1 ]]
then
  WHAT='HEAD'
else
  WHAT=$1
fi

REPO=$(git config --get remote.origin.url | sed -n 's/.*:\(.*\)\.git/\1/p')
SHA=`git rev-parse $WHAT`

if [[ -z `git branch -a --contains $SHA | grep origin` ]]
then
  echo "You have not yet pushed that commit ($SHA) to GitHub."
  echo "Before you can view it on the GitHub website, you must push it."
else
  gnome-open "https://github.com/$REPO/commit/$SHA"
fi
