#!/usr/bin/env ruby
require 'rubygems'
require 'yaml'

`ping -c 1 google.com`
if $?.exitstatus != 0
  puts 'UNABLE TO SYNC REPOS AS NW IS DOWN'
  exit $?.exitstatus
end

puts 'syncing repositories'

@repos = YAML::load_file File.expand_path( '/home/minhajuddin/.sync-repos')

@repos.each do |repo|
  path = File.expand_path repo[:path]
  remotes = repo[:remotes].is_a?(String) ? [repo[:remotes]] : repo[:remotes]
  unless File.exist? path
    puts "skipping #{path} as directory not found"
    next
  end

  remotes.each do |remote|
    cmd = "cd #{path} && git push #{remote}"
    puts "executing: '#{cmd}'"
    system(cmd)
  end
end

puts 'done syncing repositories'
